# Retail Data Wrangling and Analytics

## Load SQL into Dataframe

In [0]:
%python
retail_df = spark.sql("SELECT * FROM `jrvs_data_analytics_workspace`.`default`.`retail`;")
retail_df.head()

Row(invoice_no='561807', stock_code='23286', description='BLUE VINTAGE SPOT BEAKER', quantity=8, invoice_date=datetime.datetime(2011, 7, 29, 15, 2), unit_price=0.85, customer_id=17491.0, country='United Kingdom')

In [0]:
%python
retail_df.printSchema()
retail_df.toPandas().describe()

root
 |-- invoice_no: string (nullable = true)
 |-- stock_code: string (nullable = true)
 |-- description: string (nullable = true)
 |-- quantity: long (nullable = true)
 |-- invoice_date: timestamp (nullable = true)
 |-- unit_price: double (nullable = true)
 |-- customer_id: double (nullable = true)
 |-- country: string (nullable = true)

           quantity    unit_price    customer_id
count  1.067371e+06  1.067371e+06  824364.000000
mean   9.938898e+00  4.649388e+00   15324.638504
std    1.727058e+02  1.235531e+02    1697.464450
min   -8.099500e+04 -5.359436e+04   12346.000000
25%    1.000000e+00  1.250000e+00   13975.000000
50%    3.000000e+00  2.100000e+00   15255.000000
75%    1.000000e+01  4.150000e+00   16797.000000
max    8.099500e+04  3.897000e+04   18287.000000

## Total Invoice Amount Distribution

In [0]:
%python
from pyspark.sql.functions import col, sum, max, min, median, mode, mean

df_filtered = retail_df.filter((col("quantity") > 0) & (col("unit_price") > 0))

df_filtered = df_filtered.withColumn("amount", col("quantity") * col("unit_price"))
invoice_totals = df_filtered.groupBy("invoice_no").agg(sum("amount").alias("amount"))
print(f"Max: ${invoice_totals.select(max("amount")).first()[0]}")
print(f"Min: ${invoice_totals.select(min("amount")).first()[0]}")
print(f"Mean: ${invoice_totals.select(mean("amount")).first()[0]}")
print(f"Median: ${invoice_totals.select(median("amount")).first()[0]}")
print(f"Mode: ${invoice_totals.select(mode("amount")).first()[0]}")
display(invoice_totals)

Max: $168469.6
Min: $0.19
Mean: $523.3037611158238
Median: $304.3150000000001
Mode: $15.0

invoice_no,amount
489677,192.0
491045,303.2
491658,155.05999999999997
493542,118.75
493977,275.95
494244,6711.0
494277,1335.92
495185,2507.06
495783,48.96
496171,199.29999999999998
496233,188.82999999999998
496427,291.14000000000004
497229,312.5899999999999
498070,207.15000000000006
498125,190.95000000000005
498328,275.04
498934,899.0
500148,431.59000000000015
500253,18.85
500903,2655.96
500979,11.9
501046,612.0
501304,270.9200000000001
502610,1103.85
502620,172.35
502860,106.96000000000001
503942,304.33
504328,355.18999999999994
504372,315.84999999999997
505024,216.54
505703,328.48
506092,105.71
506258,306.2
507206,673.8599999999998
507425,360.9000000000001
507464,1621.7999999999997
508195,207.35999999999999
508647,60.0
508840,112.94
508905,160.4
508953,100.8
509891,4.25
510434,30.499999999999993
510436,180.65
510516,270.04999999999995
510761,65.05000000000001
511135,511.0399999999999
511668,319.6
511761,298.55
511789,433.97999999999996
513264,765.0
513575,333.6
513652,185.46
514019,313.94999999999993
514838,135.46000000000004
514951,162.24
515016,273.96000000000004
489460,485.7900000000001
489812,597.6899999999999
489824,176.87999999999997
489915,54.599999999999994
490100,869.9300000000001
490465,933.35
490526,533.9699999999999
490534,263.67999999999995
490538,504.53999999999996
490657,208.83
490881,10.0
491394,404.82
491724,124.89999999999999
492785,485.40000000000003
493816,212.0
494395,953.5000000000006
494997,228.96
498350,299.52000000000004
498648,367.6
499971,268.67999999999995
501464,205.56
501850,144.35000000000002
502663,146.68
502865,271.05
503531,222.11
503720,332.37
503730,359.83
503791,142.8
503812,135.55
504838,595.54
505555,211.15000000000003
505787,454.15
507687,837.1100000000001
507707,1926.4
508463,136.70000000000002
508733,610.34
508904,245.47999999999993
508993,233.04999999999998
509136,247.19000000000003
510110,109.54000000000002
510188,428.6799999999999
510444,153.35999999999999
510484,155.21
510995,340.57
511160,291.33
511632,275.84000000000003
512303,161.4
512612,395.1
512936,368.2
514008,306.78000000000003
489517,282.46000000000004
490394,870.28
490466,183.59999999999997
490545,34.0
490698,4.25
490770,135.94000000000003
490945,97.55
491136,343.52000000000004
492227,334.5
493922,194.1
494391,164.34000000000003
495188,588.4499999999999
495289,302.4
495763,107.14
495801,77.52
496155,305.4
498400,136.93
499386,109.59
499962,208.92000000000002
500198,721.4599999999998
502423,1083.0500000000006
502617,525.3399999999999
502893,401.6499999999999
503832,360.59999999999997
503877,206.6600000000001
504433,120.51000000000002
504634,236.64
504711,378.59999999999985
504890,599.4399999999998
505576,289.94
506947,145.28
507001,94.53
507026,331.54999999999995
507167,20.0
507613,286.11999999999995
507617,252.84
508080,768.44
508183,526.7099999999999
508222,645.35
509020,60.55
509463,98.84
510505,272.62
511097,335.1800000000002
512072,128.95000000000002
512557,108.0
512827,486.90000000000003
512945,405.15000000000003
513415,31.8
513876,751.4999999999998
514806,149.12000000000003
489582,293.95
489804,251.17000000000002
490116,122.39999999999999
490541,294.79999999999995
490717,449.95
491077,433.0499999999998
491191,71.78999999999999
492051,870.8400000000001
492582,322.6000000000001
493702,1600.0
493757,635.85
493804,332.5799999999999
494275,534.6
494638,278.47
494676,144.09999999999997
494995,301.5799999999999
496063,392.82
496429,246.75
496596,199.55
497518,199.03999999999996
498124,357.39
498276,398.1
500177,224.79999999999995
500458,78.0
500504,23.35
500505,445.44000000000005
500660,212.9
501148,1968.9800000000005
502108,238.5
502235,260.7499999999999
502653,312.4599999999999
502864,415.71000000000004
502976,193.82999999999996
502980,117.00999999999999
503847,147.12
504416,159.00000000000003
504469,263.2
504865,174.61
506115,234.75000000000003
506889,76.02
507035,315.82
507407,667.45
507413,111.94000000000001
507421,269.65000000000003
507536,301.09000000000003
508214,634.1300000000001
509203,14.7
509355,151.90000000000003
511121,125.4
511851,327.1599999999999
511860,381.6
512306,1575.98
512900,359.34999999999997
513401,304.61999999999995
513434,92.75
513778,172.59999999999988
514678,20.16
514835,1402.93
514849,58.5
515353,1792.090000000001
489725,216.0
489785,333.67
490693,190.46999999999997
490733,412.6
491317,683.91
491629,308.81
491640,406.12
491742,22.5
491981,381.22
492742,1636.4299999999998
494385,486.64
495150,149.0
495358,924.6400000000001
495780,16.33
496306,310.39
496369,100.99000000000001
497039,102.84
497393,275.40999999999997
497605,6.35
497885,736.4400000000002
497912,699.9300000000001
498018,239.14000000000001
498240,549.4999999999999
499452,142.15
501661,312.97
501902,381.0
502102,284.03999999999996
502612,3.75
505742,324.44
505987,1480.37
508190,549.6200000000001
508356,7.9
509033,491.8799999999998
509981,14.98
510035,202.16000000000003
510413,227.78000000000003
511440,97.5
511929,101.35000000000001
511961,1575.26
512587,186.05999999999997
512800,249.48000000000002
513197,148.85
513915,108.06
514059,624.12
514097,1799.0699999999995
514514,371.6899999999999
489616,409.27000000000004
490430,253.55
490476,211.62
490490,547.7300000000001
491033,328.02
491048,519.42
491498,209.59000000000003
492007,169.5
492209,236.16999999999993
493372,643.6999999999999
494281,317.64
495745,56.73
496066,346.56
496863,585.0299999999999
497203,484.91
497433,105.0
497584,4.1499999999999995
497743,150.39000000000001
497959,171.60000000000002
498756,1110.48
499775,68.28
500098,718.21
500173,5525.28
501263,126.48
501624,319.03
501626,57.82000000000001
502816,299.00000000000006
502916,236.54999999999995
503711,47.5
505375,4.65
506174,714.0
506293,1898.5700000000006
507237,69.84
508103,115.08000000000001
509018,4.2
509451,279.25
509637,305.15
510586,305.86
511027,513.26
511247,322.62999999999994
511791,971.26
511798,51.0
512088,106.08999999999999
512301,252.45
512750,125.65
512914,175.5
513190,1272.1600000000014
513796,219.35000000000002
513992,1044.21
514470,306.63
489895,371.82
490009,285.09000000000003
490537,209.41
490708,241.05
492234,297.4
493540,165.0
493720,551.45
494359,383.0199999999999
494648,454.90000000000015
494798,376.25
497588,132.94000000000003
497625,311.87
498153,147.64000000000001
498508,590.9099999999999
500238,116.5
501299,112.9
502427,363.5099999999998
502867,284.64000000000004
503827,405.0
503991,762.2800000000003
504082,368.3899999999999
505227,874.84
506229,153.0
506443,578.9
506740,269.34
507027,364.50000000000006
507400,86.44
507434,166.53
508226,192.89
508505,91.22000000000001
508748,6250.0
511002,128.95
511514,1242.8899999999999
512092,306.3
512572,1.25
513015,427.91
513310,441.5
513490,12.75
513544,17.700000000000003
513712,108.75
513747,305.07000000000005
513799,119.8
514811,293.61000000000007
515018,607.6199999999999
515179,494.4899999999999
489864,206.85
489879,163.46999999999997
490364,103.95
490611,312.65000000000003
490707,45.900000000000006
491161,109.35
491319,181.63
491661,326.4
491813,157.5
492127,538.77
492519,299.65
492746,418.03000000000003
495818,148.63
495949,151.87
496438,129.76
496528,674.4
497402,1460.7
499039,1112.2
499900,344.57
500172,807.1199999999999
501369,299.03
502721,383.75
502724,286.58
502905,306.0
502912,579.6
503185,4977.740000000002
503905,21.599999999999998
504114,106.89
504442,124.64
504620,149.0
504908,391.49999999999994
505011,237.01999999999998
505081,115.17999999999999
505500,434.52
505891,336.54999999999995
506457,97.35
507604,1665.799999999999
508451,1540.1299999999999
508491,321.05999999999983
508864,1338.0399999999995
509194,51.0
509450,409.7
509752,572.88
510152,363.10999999999996
510442,507.41
512745,600.84
513121,15.299999999999999
513563,298.4
513803,155.51999999999998
514288,309.84999999999997
515121,259.75
515182,361.81000000000006
489783,162.04000000000002
490112,313.19
490145,989.1800000000001
490365,351.6
490638,147.1
491450,634.8800000000001
491677,15.0
493304,21.400000000000002
494209,260.15
495030,835.4499999999999
496425,282.76
496871,460.39
497227,1690.3200000000004
497254,166.9
497799,216.60000000000002
498345,293.45
499036,664.9200000000002
499057,365.9299999999999
500539,477.30000000000007
501086,128.06
501431,143.86
501651,110.26
501664,618.36
501870,411.42
502822,118.00000000000001
503430,817.2500000000001
503766,680.04
504152,335.00000000000006
504559,369.24
505507,246.88
505540,495.0
505697,325.5
506177,365.20000000000005
507396,956.93
508909,349.79999999999995
509161,384.9599999999999
509538,184.68
509979,101.99
510591,14.98
510801,301.94
510990,61.199999999999996
511021,1247.0700000000002
511218,19.799999999999997
512890,134.37
513356,387.81000000000006
514015,404.45
514126,284.19
514132,27.839999999999996
514732,283.61
515027,330.5299999999999
491449,1641.9
491456,11016.0
491644,100.55000000000001
491954,88.5
494045,435.88
494649,156.32999999999998
495398,518.35
495548,13.2
495681,495.7199999999999
496976,124.44999999999999
496979,1263.8499999999997
497163,15.0
497844,283.85
498780,1793.4600000000005
498914,389.28
499527,399.55
500653,689.45
502337,300.8
502875,243.0
502913,415.13999999999993
504146,2969.6
504479,77.55
505070,52.75000000000001
505335,3857.2
505878,80.61999999999999
506209,690.0500000000001
506224,1192.27
506407,4.95
506876,426.8499999999999
507381,440.3499999999999
507634,1149.3699999999997
507819,141.85
507923,621.9300000000002
508070,515.8
508897,194.7
509544,302.95
510136,118.64000000000001
510199,196.25000000000003
510350,135.95
510429,267.32
511771,15.0
512307,170.4
512722,139.88000000000002
513117,281.17999999999995
513186,320.19999999999993
513342,313.2
513566,358.47
513580,5.0
513605,304.2899999999999
514365,189.51000000000002
514852,348.56000000000006
489875,530.76
490090,45.550000000000004
490160,244.79999999999998
490377,15.0
490608,163.76999999999998
491008,191.89
492778,376.85
494007,136.15
494276,305.09999999999997
494336,332.7
494662,377.32
495353,159.10000000000002
495956,654.0
495962,305.7
496518,270.05999999999995
496800,1664.5900000000004
497364,651.4100000000002
498222,194.63000000000005
498724,2685.5400000000004
499229,349.0
499964,154.14
500134,314.57
500255,405.41999999999996
500886,214.12999999999997
501038,384.46
501484,331.32
501710,453.1699999999999
503798,318.09000000000003
503971,303.45
504097,392.6200000000002
504183,465.18
504974,406.7999999999999
505346,23.75
505636,386.4000000000001
505677,1.95
506444,481.65
506716,156.64999999999995
506997,324.67
508189,121.92
508201,78.57999999999997
508611,172.07999999999998
508751,158.23
509152,0.85
509399,169.32000000000002
510064,1515.97
510150,1141.62
510426,159.39999999999998
511551,356.7
511782,78.60000000000001
512270,71.4
512545,1468.1200000000001
512744,1212.4000000000003
513403,326.13
513631,180.85000000000002
514141,248.48000000000008
514728,2162.180000000001
514975,102.0
515141,134.89999999999998
489908,107.33
490054,277.5
490369,230.2
491159,291.0
491893,273.99999999999994
492250,462.95
492517,233.4
492686,3.24
493326,799.9200000000001
493813,392.95000000000005
494218,204.27999999999997
495365,501.22999999999996
497351,128.20000000000002
497923,304.37999999999994
498161,3157.0599999999995
498277,11.3
498618,1632.930000000001
498832,172.15000000000003
498927,277.12
499169,190.8
499239,160.81
500014,1449.7400000000005
500246,53.4
500323,487.75
500386,308.4
500744,602.76
501008,281.89000000000004
501544,292.9300000000001
501616,140.20000000000002
501792,313.4
501845,604.65
502495,161.5
502753,194.79999999999998
502873,381.0
503845,204.60000000000002
503982,488.29999999999995
504159,50.129999999999995
504877,316.05
504924,1372.0499999999997
505061,590.3499999999999
505202,2940.1600000000003
505398,394.00000000000006
507410,22.5
509467,337.85
510204,2837.0400000000004
510225,1449.7500000000002
510517,155.0
510647,28.23
510656,93.6
511042,179.6
511126,131.39999999999998
511304,273.49
511698,55.379999999999995
512461,449.84999999999997
512558,167.45
513469,582.1700000000001
513551,194.40000000000003
514643,1113.7000000000003
514926,329.8500000000001
515020,333.46999999999997
515149,716.0800000000003
489802,174.52000000000004
489866,1003.8299999999997
490135,387.87
491675,374.04
491719,348.61000000000007
492222,187.84000000000003
492535,286.04
492688,11.6
492695,9.15
495208,11.25
495376,139.65
495405,247.55
495880,1019.9999999999999
496918,376.95
496977,532.9300000000001
497596,380.0
497876,304.6499999999999
498613,118.00000000000001
498936,1087.52
499402,287.55
499757,191.10000000000002
502608,503.97
502671,403.28000000000003
502997,80.79999999999998
503058,313.70000000000005
503062,208.1699999999999
503778,312.5
503838,98.89999999999999
505841,453.1499999999999
505865,22.68
507467,22.549999999999997
508765,269.79999999999995
508796,925.1600000000001
508873,348.59000000000003
509374,305.28000000000003
509398,632.95
509606,124.25
510138,172.0
511271,455.57
512460,515.16
513340,181.55999999999997
513586,34.919999999999995
513751,355.43999999999994
514022,594.1700000000001
514519,270.12
489687,221.53
490936,366.9
490990,271.84999999999985
491179,7.95
491634,574.0899999999998
491815,177.84
491956,381.4000000000001
491983,415.48999999999995
492247,307.15
492356,422.35
492406,597.5
492429,1425.3000000000002
493948,1104.25
494678,3151.0
494792,235.89000000000001
495720,430.2999999999998
496083,5.1
496615,1380.3000000000002
498025,181.24
498757,427.61
498999,212.85
499650,217.86
501475,1493.7700000000002
501509,155.64000000000004
501515,298.43999999999994
501573,595.0999999999998
501627,91.8
502874,348.46999999999997
503064,215.92
503542,2831.66
503901,196.07999999999996
503976,277.85
504533,101.75999999999999
504630,19.799999999999997
504635,746.3300000000004
504675,436.76
505393,45.0
505702,194.09000000000003
507194,533.7999999999997
507606,189.74000000000004
508187,311.09999999999997
509204,657.4
509573,304.11999999999995
509748,426.2400000000001
511329,484.7900000000001
511818,52.199999999999996
511947,15.44
512512,305.28000000000003
513492,199.60000000000002
514130,102.0
490094,851.76
490108,239.68
490258,20.4
490506,25.460000000000004
490747,8.92
490808,134.04000000000002
490933,2452.56
490950,6.35
490982,8.82
491081,307.99999999999994
491691,386.73
491736,756.5100000000003
491757,705.5999999999999
492077,290.72
493077,313.6
493762,414.71999999999997
495230,724.9200000000002
495731,267.78999999999996
497609,117.80000000000001
497931,1709.0
498381,18.049999999999997
498642,826.1500000000002
498879,289.6
498928,4168.98
499486,1422.7800000000002
499509,34.0
499781,644.2500000000001
500334,315.28000000000003
500577,166.48000000000002
501892,167.64999999999992
502920,142.11999999999998
503234,339.16999999999996
503448,524.3899999999999
504421,394.24
505187,234.6
505740,391.67999999999995
506140,462.69999999999993
506478,396.0
507119,63.5
507193,595.1800000000001
507436,158.6
507447,119.35000000000001
508867,310.35
509707,1.7
509970,155.65000000000003
511092,326.8500000000001
511274,152.10000000000002
511954,319.38000000000005
512289,1287.7800000000004
512522,611.9399999999999
512464,47.7
512511,30.24
512556,160.07999999999998
512925,147.39999999999998
513965,686.3999999999996
514692,145.5
515409,426.26000000000005
489870,162.1
490023,189.15
490675,696.5400000000001
491726,1081.6599999999999
492238,520.46
492545,139.0
492547,424.29999999999984
495710,630.7899999999998
497615,286.55
498162,223.2
498925,369.0
499267,2320.03
499961,1085.0100000000002
500267,599.12
500274,152.82
500311,451.88
500336,619.04
500367,348.31999999999994
500701,178.36
500837,113.53
500868,551.9499999999999
501291,475.53999999999985
501564,197.38
502824,127.65
503394,299.34000000000003
503797,482.58000000000004
503823,1981.5099999999989
503851,816.0
504589,399.6000000000001
505981,5416.799999999999
507158,948.1300000000002
507479,313.8
507689,339.8
508500,491.98000000000013
508745,41.050000000000004
509383,371.13999999999993
510331,1458.7099999999998
510625,266.24999999999994
511006,462.4799999999999
511447,13.919999999999998
511762,299.3299999999999
511957,172.05
512077,908.3800000000001
512897,4.14
513329,66.72
513359,49.41
513599,61.74
515025,304.97
491094,216.0
491180,294.5199999999999
491969,6141.939999999991
492204,322.91999999999996
494272,321.44
495510,183.92999999999995
496507,176.09999999999997
497716,660.0
497880,254.92
499165,597.7599999999999
499887,124.04999999999998
500749,2017.3599999999997
501795,248.8
501802,3.7399999999999998
501821,274.63
502595,736.1000000000001
502662,119.83999999999995
503338,190.95
503572,441.55
503593,178.2
503604,450.8499999999999
503848,187.35000000000002
504447,33.849999999999994
504473,611.6999999999999
504582,447.45000000000005
504644,526.1399999999999
504827,43.449999999999996
505361,126.58000000000001
505573,276.86
506822,69.75
507641,135.39000000000001
508311,556.55
508622,341.0
509141,214.65
509189,337.74
510157,568.8199999999999
510411,202.24999999999997
510539,2051.84
511029,311.66
511335,6007.68
512598,114.84999999999998
513615,725.3100000000002
513987,2326.7399999999993
514858,81.36
489664,374.43
489877,368.1
489904,203.77999999999997
489932,82.60000000000001
490008,503.93000000000006
490468,204.24000000000004
490668,312.33
490948,15.0
490971,372.64000000000004
491070,383.80000000000007
491734,950.0
492360,584.1000000000003
492549,339.9
495070,5750.760000000004
496107,10.600000000000001
496336,21.27
496442,45.2
496461,312.15999999999997
497795,935.83
498098,171.24999999999997
498507,546.5999999999999
499507,238.4
501118,405.0
502755,67.25
503335,308.60999999999996
503341,560.1399999999999
503828,636.5999999999999
503862,19.0
504139,707.7800000000001
504915,764.38
505552,19.799999999999997
505685,230.10999999999999
505776,73.5
506172,236.28000000000003
507022,8.42
507052,302.35
507839,43.65
509117,323.03999999999996
509576,351.26000000000005
509631,398.6299999999999
509870,306.74000000000007
510161,91.40000000000002
511556,3330.5200000000004
511635,337.90999999999997
511778,2199.390000000001
512078,612.0
512102,363.62999999999994
512748,955.06
513019,394.39
513118,19.9
513664,166.35
513744,730.9
513942,1544.6599999999996
513951,8.9
513964,1765.9500000000003
514163,622.2599999999995
514337,102.70000000000002
514554,148.32
514864,410.56000000000006
515265,205.74
490705,204.0
491358,99.6
491464,52.800000000000004
492178,340.39
493826,49.20000000000001
494119,559.96
494145,4.95
494872,286.43
494917,183.2000000000001
495960,586.8800000000001
496003,113.19000000000003
496059,20.0
496357,436.04
496774,300.3
496945,1042.88
497612,131.78000000000003
497988,165.72
498041,211.94000000000003
498121,199.70000000000002
500730,551.2
501471,305.40999999999997
501770,318.06
502057,49.3
502239,190.5
502266,241.89999999999998
502497,26.450000000000003
503784,1187.9
503956,521.5400000000001
504137,1149.5800000000002
504584,124.62
504688,94.8
505023,689.4599999999998
505147,703.2199999999998
505176,736.8799999999999
506118,136.25
507125,153.14999999999998
507386,1063.88
508524,1193.5
508825,207.14000000000004
509145,113.49000000000001
509151,273.40999999999997
509759,1078.8100000000002
510483,311.8499999999999
511805,255.39000000000001
511853,2608.04
512403,114.45
513431,355.7
513540,1176.2
513794,314.7
514091,330.0
515180,376.6
490114,257.62
490375,350.54999999999995
490464,118.26000000000002
490863,88.05000000000001
491181,592.2
493067,99.46000000000004
493880,563.98
493955,1190.4600000000003
493988,300.6
494011,1620.7500000000002
494479,858.25
495171,133.15
495584,229.59
496467,818.19
498292,51.0
498501,64.6
498908,222.53000000000003
499177,15.55
499533,136.07999999999998
499633,319.08000000000004
500741,1108.85
501767,728.37
501807,494.99000000000007
503248,282.0
503516,162.1
504020,613.1
504176,9.87
504878,551.4199999999998
504897,1.95
505328,182.76999999999998
505588,158.08999999999997
505616,325.15000000000003
505715,298.32
506271,117.0
506558,125.77999999999999
507113,302.3
507180,310.16
507205,350.38
507232,354.24000000000007
507586,436.47
508049,212.0
508061,192.96
508335,120.0
509039,389.1
509940,193.2
510063,593.45
510067,1894.34
510239,610.1
510338,311.75
510352,171.18
511079,36.9
511185,118.3

Databricks visualization. Run in Databricks to view.

In [0]:
%python
q85 = invoice_totals.approxQuantile("amount", [0.85], 0.01)[0]
q85_invoices = invoice_totals.filter(col("amount") <= q85)

print(f"Max: ${q85_invoices.select(max("amount")).first()[0]}")
print(f"Min: ${q85_invoices.select(min("amount")).first()[0]}")
print(f"Mean: ${q85_invoices.select(mean("amount")).first()[0]}")
print(f"Median: ${q85_invoices.select(median("amount")).first()[0]}")
print(f"Mode: ${q85_invoices.select(mode("amount")).first()[0]}")
display(q85_invoices)

Max: $692.96
Min: $0.19
Mean: $266.9204015252676
Median: $253.02
Mode: $15.0

invoice_no,amount
489677,192.0
491045,303.2
491658,155.05999999999997
493542,118.75
493977,275.95
495783,48.96
496171,199.29999999999998
496233,188.82999999999998
496427,291.14000000000004
497229,312.5899999999999
498070,207.15000000000006
498125,190.95000000000005
498328,275.04
500148,431.59000000000015
500253,18.85
500979,11.9
501046,612.0
501304,270.9200000000001
502620,172.35
502860,106.96000000000001
503942,304.33
504328,355.18999999999994
504372,315.84999999999997
505024,216.54
505703,328.48
506092,105.71
506258,306.2
507206,673.8599999999998
507425,360.9000000000001
508195,207.35999999999999
508647,60.0
508840,112.94
508905,160.4
508953,100.8
509891,4.25
510434,30.499999999999993
510436,180.65
510516,270.04999999999995
510761,65.05000000000001
511135,511.0399999999999
511668,319.6
511761,298.55
511789,433.97999999999996
513575,333.6
513652,185.46
514019,313.94999999999993
514838,135.46000000000004
514951,162.24
515016,273.96000000000004
489460,485.7900000000001
489812,597.6899999999999
489824,176.87999999999997
489915,54.599999999999994
490526,533.9699999999999
490534,263.67999999999995
490538,504.53999999999996
490657,208.83
490881,10.0
491394,404.82
491724,124.89999999999999
492785,485.40000000000003
493816,212.0
494997,228.96
498350,299.52000000000004
498648,367.6
499971,268.67999999999995
501464,205.56
501850,144.35000000000002
502663,146.68
502865,271.05
503531,222.11
503720,332.37
503730,359.83
503791,142.8
503812,135.55
504838,595.54
505555,211.15000000000003
505787,454.15
508463,136.70000000000002
508733,610.34
508904,245.47999999999993
508993,233.04999999999998
509136,247.19000000000003
510110,109.54000000000002
510188,428.6799999999999
510444,153.35999999999999
510484,155.21
510995,340.57
511160,291.33
511632,275.84000000000003
512303,161.4
512612,395.1
512936,368.2
514008,306.78000000000003
489517,282.46000000000004
490466,183.59999999999997
490545,34.0
490698,4.25
490770,135.94000000000003
490945,97.55
491136,343.52000000000004
492227,334.5
493922,194.1
494391,164.34000000000003
495188,588.4499999999999
495289,302.4
495763,107.14
495801,77.52
496155,305.4
498400,136.93
499386,109.59
499962,208.92000000000002
502617,525.3399999999999
502893,401.6499999999999
503832,360.59999999999997
503877,206.6600000000001
504433,120.51000000000002
504634,236.64
504711,378.59999999999985
504890,599.4399999999998
505576,289.94
506947,145.28
507001,94.53
507026,331.54999999999995
507167,20.0
507613,286.11999999999995
507617,252.84
508183,526.7099999999999
508222,645.35
509020,60.55
509463,98.84
510505,272.62
511097,335.1800000000002
512072,128.95000000000002
512557,108.0
512827,486.90000000000003
512945,405.15000000000003
513415,31.8
514806,149.12000000000003
489582,293.95
489804,251.17000000000002
490116,122.39999999999999
490541,294.79999999999995
490717,449.95
491077,433.0499999999998
491191,71.78999999999999
492582,322.6000000000001
493757,635.85
493804,332.5799999999999
494275,534.6
494638,278.47
494676,144.09999999999997
494995,301.5799999999999
496063,392.82
496429,246.75
496596,199.55
497518,199.03999999999996
498124,357.39
498276,398.1
500177,224.79999999999995
500458,78.0
500504,23.35
500505,445.44000000000005
500660,212.9
502108,238.5
502235,260.7499999999999
502653,312.4599999999999
502864,415.71000000000004
502976,193.82999999999996
502980,117.00999999999999
503847,147.12
504416,159.00000000000003
504469,263.2
504865,174.61
506115,234.75000000000003
506889,76.02
507035,315.82
507407,667.45
507413,111.94000000000001
507421,269.65000000000003
507536,301.09000000000003
508214,634.1300000000001
509203,14.7
509355,151.90000000000003
511121,125.4
511851,327.1599999999999
511860,381.6
512900,359.34999999999997
513401,304.61999999999995
513434,92.75
513778,172.59999999999988
514678,20.16
514849,58.5
489725,216.0
489785,333.67
490693,190.46999999999997
490733,412.6
491317,683.91
491629,308.81
491640,406.12
491742,22.5
491981,381.22
494385,486.64
495150,149.0
495780,16.33
496306,310.39
496369,100.99000000000001
497039,102.84
497393,275.40999999999997
497605,6.35
498018,239.14000000000001
498240,549.4999999999999
499452,142.15
501661,312.97
501902,381.0
502102,284.03999999999996
502612,3.75
505742,324.44
508190,549.6200000000001
508356,7.9
509033,491.8799999999998
509981,14.98
510035,202.16000000000003
510413,227.78000000000003
511440,97.5
511929,101.35000000000001
512587,186.05999999999997
512800,249.48000000000002
513197,148.85
513915,108.06
514059,624.12
514514,371.6899999999999
489616,409.27000000000004
490430,253.55
490476,211.62
490490,547.7300000000001
491033,328.02
491048,519.42
491498,209.59000000000003
492007,169.5
492209,236.16999999999993
493372,643.6999999999999
494281,317.64
495745,56.73
496066,346.56
496863,585.0299999999999
497203,484.91
497433,105.0
497584,4.1499999999999995
497743,150.39000000000001
497959,171.60000000000002
499775,68.28
501263,126.48
501624,319.03
501626,57.82000000000001
502816,299.00000000000006
502916,236.54999999999995
503711,47.5
505375,4.65
507237,69.84
508103,115.08000000000001
509018,4.2
509451,279.25
509637,305.15
510586,305.86
511027,513.26
511247,322.62999999999994
511798,51.0
512088,106.08999999999999
512301,252.45
512750,125.65
512914,175.5
513796,219.35000000000002
514470,306.63
489895,371.82
490009,285.09000000000003
490537,209.41
490708,241.05
492234,297.4
493540,165.0
493720,551.45
494359,383.0199999999999
494648,454.90000000000015
494798,376.25
497588,132.94000000000003
497625,311.87
498153,147.64000000000001
498508,590.9099999999999
500238,116.5
501299,112.9
502427,363.5099999999998
502867,284.64000000000004
503827,405.0
504082,368.3899999999999
506229,153.0
506443,578.9
506740,269.34
507027,364.50000000000006
507400,86.44
507434,166.53
508226,192.89
508505,91.22000000000001
511002,128.95
512092,306.3
512572,1.25
513015,427.91
513310,441.5
513490,12.75
513544,17.700000000000003
513712,108.75
513747,305.07000000000005
513799,119.8
514811,293.61000000000007
515018,607.6199999999999
515179,494.4899999999999
489864,206.85
489879,163.46999999999997
490364,103.95
490611,312.65000000000003
490707,45.900000000000006
491161,109.35
491319,181.63
491661,326.4
491813,157.5
492127,538.77
492519,299.65
492746,418.03000000000003
495818,148.63
495949,151.87
496438,129.76
496528,674.4
499900,344.57
501369,299.03
502721,383.75
502724,286.58
502905,306.0
502912,579.6
503905,21.599999999999998
504114,106.89
504442,124.64
504620,149.0
504908,391.49999999999994
505011,237.01999999999998
505081,115.17999999999999
505500,434.52
505891,336.54999999999995
506457,97.35
508491,321.05999999999983
509194,51.0
509450,409.7
509752,572.88
510152,363.10999999999996
510442,507.41
512745,600.84
513121,15.299999999999999
513563,298.4
513803,155.51999999999998
514288,309.84999999999997
515121,259.75
515182,361.81000000000006
489783,162.04000000000002
490112,313.19
490365,351.6
490638,147.1
491450,634.8800000000001
491677,15.0
493304,21.400000000000002
494209,260.15
496425,282.76
496871,460.39
497254,166.9
497799,216.60000000000002
498345,293.45
499036,664.9200000000002
499057,365.9299999999999
500539,477.30000000000007
501086,128.06
501431,143.86
501651,110.26
501664,618.36
501870,411.42
502822,118.00000000000001
503766,680.04
504152,335.00000000000006
504559,369.24
505507,246.88
505540,495.0
505697,325.5
506177,365.20000000000005
508909,349.79999999999995
509161,384.9599999999999
509538,184.68
509979,101.99
510591,14.98
510801,301.94
510990,61.199999999999996
511218,19.799999999999997
512890,134.37
513356,387.81000000000006
514015,404.45
514126,284.19
514132,27.839999999999996
514732,283.61
515027,330.5299999999999
491644,100.55000000000001
491954,88.5
494045,435.88
494649,156.32999999999998
495398,518.35
495548,13.2
495681,495.7199999999999
496976,124.44999999999999
497163,15.0
497844,283.85
498914,389.28
499527,399.55
500653,689.45
502337,300.8
502875,243.0
502913,415.13999999999993
504479,77.55
505070,52.75000000000001
505878,80.61999999999999
506209,690.0500000000001
506407,4.95
506876,426.8499999999999
507381,440.3499999999999
507819,141.85
507923,621.9300000000002
508070,515.8
508897,194.7
509544,302.95
510136,118.64000000000001
510199,196.25000000000003
510350,135.95
510429,267.32
511771,15.0
512307,170.4
512722,139.88000000000002
513117,281.17999999999995
513186,320.19999999999993
513342,313.2
513566,358.47
513580,5.0
513605,304.2899999999999
514365,189.51000000000002
514852,348.56000000000006
489875,530.76
490090,45.550000000000004
490160,244.79999999999998
490377,15.0
490608,163.76999999999998
491008,191.89
492778,376.85
494007,136.15
494276,305.09999999999997
494336,332.7
494662,377.32
495353,159.10000000000002
495956,654.0
495962,305.7
496518,270.05999999999995
497364,651.4100000000002
498222,194.63000000000005
499229,349.0
499964,154.14
500134,314.57
500255,405.41999999999996
500886,214.12999999999997
501038,384.46
501484,331.32
501710,453.1699999999999
503798,318.09000000000003
503971,303.45
504097,392.6200000000002
504183,465.18
504974,406.7999999999999
505346,23.75
505636,386.4000000000001
505677,1.95
506444,481.65
506716,156.64999999999995
506997,324.67
508189,121.92
508201,78.57999999999997
508611,172.07999999999998
508751,158.23
509152,0.85
509399,169.32000000000002
510426,159.39999999999998
511551,356.7
511782,78.60000000000001
512270,71.4
513403,326.13
513631,180.85000000000002
514141,248.48000000000008
514975,102.0
515141,134.89999999999998
489908,107.33
490054,277.5
490369,230.2
491159,291.0
491893,273.99999999999994
492250,462.95
492517,233.4
492686,3.24
493813,392.95000000000005
494218,204.27999999999997
495365,501.22999999999996
497351,128.20000000000002
497923,304.37999999999994
498277,11.3
498832,172.15000000000003
498927,277.12
499169,190.8
499239,160.81
500246,53.4
500323,487.75
500386,308.4
500744,602.76
501008,281.89000000000004
501544,292.9300000000001
501616,140.20000000000002
501792,313.4
501845,604.65
502495,161.5
502753,194.79999999999998
502873,381.0
503845,204.60000000000002
503982,488.29999999999995
504159,50.129999999999995
504877,316.05
505061,590.3499999999999
505398,394.00000000000006
507410,22.5
509467,337.85
510517,155.0
510647,28.23
510656,93.6
511042,179.6
511126,131.39999999999998
511304,273.49
511698,55.379999999999995
512461,449.84999999999997
512558,167.45
513469,582.1700000000001
513551,194.40000000000003
514926,329.8500000000001
515020,333.46999999999997
489802,174.52000000000004
490135,387.87
491675,374.04
491719,348.61000000000007
492222,187.84000000000003
492535,286.04
492688,11.6
492695,9.15
495208,11.25
495376,139.65
495405,247.55
496918,376.95
496977,532.9300000000001
497596,380.0
497876,304.6499999999999
498613,118.00000000000001
499402,287.55
499757,191.10000000000002
502608,503.97
502671,403.28000000000003
502997,80.79999999999998
503058,313.70000000000005
503062,208.1699999999999
503778,312.5
503838,98.89999999999999
505841,453.1499999999999
505865,22.68
507467,22.549999999999997
508765,269.79999999999995
508873,348.59000000000003
509374,305.28000000000003
509398,632.95
509606,124.25
510138,172.0
511271,455.57
512460,515.16
513340,181.55999999999997
513586,34.919999999999995
513751,355.43999999999994
514022,594.1700000000001
514519,270.12
489687,221.53
490936,366.9
490990,271.84999999999985
491179,7.95
491634,574.0899999999998
491815,177.84
491956,381.4000000000001
491983,415.48999999999995
492247,307.15
492356,422.35
492406,597.5
494792,235.89000000000001
495720,430.2999999999998
496083,5.1
498025,181.24
498757,427.61
498999,212.85
499650,217.86
501509,155.64000000000004
501515,298.43999999999994
501573,595.0999999999998
501627,91.8
502874,348.46999999999997
503064,215.92
503901,196.07999999999996
503976,277.85
504533,101.75999999999999
504630,19.799999999999997
504675,436.76
505393,45.0
505702,194.09000000000003
507194,533.7999999999997
507606,189.74000000000004
508187,311.09999999999997
509204,657.4
509573,304.11999999999995
509748,426.2400000000001
511329,484.7900000000001
511818,52.199999999999996
511947,15.44
512512,305.28000000000003
513492,199.60000000000002
514130,102.0
490108,239.68
490258,20.4
490506,25.460000000000004
490747,8.92
490808,134.04000000000002
490950,6.35
490982,8.82
491081,307.99999999999994
491691,386.73
492077,290.72
493077,313.6
493762,414.71999999999997
495731,267.78999999999996
497609,117.80000000000001
498381,18.049999999999997
498879,289.6
499509,34.0
499781,644.2500000000001
500334,315.28000000000003
500577,166.48000000000002
501892,167.64999999999992
502920,142.11999999999998
503234,339.16999999999996
503448,524.3899999999999
504421,394.24
505187,234.6
505740,391.67999999999995
506140,462.69999999999993
506478,396.0
507119,63.5
507193,595.1800000000001
507436,158.6
507447,119.35000000000001
508867,310.35
509707,1.7
509970,155.65000000000003
511092,326.8500000000001
511274,152.10000000000002
511954,319.38000000000005
512522,611.9399999999999
512464,47.7
512511,30.24
512556,160.07999999999998
512925,147.39999999999998
513965,686.3999999999996
514692,145.5
515409,426.26000000000005
489870,162.1
490023,189.15
492238,520.46
492545,139.0
492547,424.29999999999984
495710,630.7899999999998
497615,286.55
498162,223.2
498925,369.0
500267,599.12
500274,152.82
500311,451.88
500336,619.04
500367,348.31999999999994
500701,178.36
500837,113.53
500868,551.9499999999999
501291,475.53999999999985
501564,197.38
502824,127.65
503394,299.34000000000003
503797,482.58000000000004
504589,399.6000000000001
507479,313.8
507689,339.8
508500,491.98000000000013
508745,41.050000000000004
509383,371.13999999999993
510625,266.24999999999994
511006,462.4799999999999
511447,13.919999999999998
511762,299.3299999999999
511957,172.05
512897,4.14
513329,66.72
513359,49.41
513599,61.74
515025,304.97
491094,216.0
491180,294.5199999999999
492204,322.91999999999996
494272,321.44
495510,183.92999999999995
496507,176.09999999999997
497716,660.0
497880,254.92
499165,597.7599999999999
499887,124.04999999999998
501795,248.8
501802,3.7399999999999998
501821,274.63
502662,119.83999999999995
503338,190.95
503572,441.55
503593,178.2
503604,450.8499999999999
503848,187.35000000000002
504447,33.849999999999994
504473,611.6999999999999
504582,447.45000000000005
504644,526.1399999999999
504827,43.449999999999996
505361,126.58000000000001
505573,276.86
506822,69.75
507641,135.39000000000001
508311,556.55
508622,341.0
509141,214.65
509189,337.74
510157,568.8199999999999
510411,202.24999999999997
511029,311.66
512598,114.84999999999998
514858,81.36
489664,374.43
489877,368.1
489904,203.77999999999997
489932,82.60000000000001
490008,503.93000000000006
490468,204.24000000000004
490668,312.33
490948,15.0
490971,372.64000000000004
491070,383.80000000000007
492360,584.1000000000003
492549,339.9
496107,10.600000000000001
496336,21.27
496442,45.2
496461,312.15999999999997
498098,171.24999999999997
498507,546.5999999999999
499507,238.4
501118,405.0
502755,67.25
503335,308.60999999999996
503341,560.1399999999999
503828,636.5999999999999
503862,19.0
505552,19.799999999999997
505685,230.10999999999999
505776,73.5
506172,236.28000000000003
507022,8.42
507052,302.35
507839,43.65
509117,323.03999999999996
509576,351.26000000000005
509631,398.6299999999999
509870,306.74000000000007
510161,91.40000000000002
511635,337.90999999999997
512078,612.0
512102,363.62999999999994
513019,394.39
513118,19.9
513664,166.35
513951,8.9
514163,622.2599999999995
514337,102.70000000000002
514554,148.32
514864,410.56000000000006
515265,205.74
490705,204.0
491358,99.6
491464,52.800000000000004
492178,340.39
493826,49.20000000000001
494119,559.96
494145,4.95
494872,286.43
494917,183.2000000000001
495960,586.8800000000001
496003,113.19000000000003
496059,20.0
496357,436.04
496774,300.3
497612,131.78000000000003
497988,165.72
498041,211.94000000000003
498121,199.70000000000002
500730,551.2
501471,305.40999999999997
501770,318.06
502057,49.3
502239,190.5
502266,241.89999999999998
502497,26.450000000000003
503956,521.5400000000001
504584,124.62
504688,94.8
505023,689.4599999999998
506118,136.25
507125,153.14999999999998
508825,207.14000000000004
509145,113.49000000000001
509151,273.40999999999997
510483,311.8499999999999
511805,255.39000000000001
512403,114.45
513431,355.7
513794,314.7
514091,330.0
515180,376.6
490114,257.62
490375,350.54999999999995
490464,118.26000000000002
490863,88.05000000000001
491181,592.2
493067,99.46000000000004
493880,563.98
493988,300.6
495171,133.15
495584,229.59
498292,51.0
498501,64.6
498908,222.53000000000003
499177,15.55
499533,136.07999999999998
499633,319.08000000000004
501807,494.99000000000007
503248,282.0
503516,162.1
504020,613.1
504176,9.87
504878,551.4199999999998
504897,1.95
505328,182.76999999999998
505588,158.08999999999997
505616,325.15000000000003
505715,298.32
506271,117.0
506558,125.77999999999999
507113,302.3
507180,310.16
507205,350.38
507232,354.24000000000007
507586,436.47
508049,212.0
508061,192.96
508335,120.0
509039,389.1
509940,193.2
510063,593.45
510239,610.1
510338,311.75
510352,171.18
511079,36.9
511185,118.3
511512,196.34999999999997
511573,10.2
512055,164.54999999999998
512456,118.88000000000001
512940,250.3
513368,517.72
513409,469.38000000000005
513614,212.63000000000002
513628,174.80000000000004
515426,80.15
489435,145.79999999999998
489574,551.3299999999998
489614,408.85
490019,308.6
490802,19.5
491782,162.25
492208,334.14
492929,371.55
493438,360.0
494616,110.72
494897,537.7800000000001
496368,103.46000000000002
496512,420.25999999999993
497261,154.38
497510,55.5
498021,129.33999999999997
498099,196.59999999999994
498106,164.09
500128,128.55
500885,412.2
501403,46.8
501442,517.9499999999998
503954,316.40999999999997
504001,254.99999999999997
504640,638.5199999999999
504859,354.33000000000004
505357,302.0
506571,408.4
506843,459.55000000000007
508235,583.56
508614,308.8
509173,495.24
509430,363.6
509856,429.0
509937,322.87999999999994
511096,573.86
511401,343.4500000000001
512953,53.1
514682,579.3499999999999
489572,507.48999999999967
490045,180.39000000000001
490340,630.39
490345,6.7
490391,304.09999999999997
490494,192.27000000000004
491096,175.95000000000002
491683,361.54999999999995
492245,243.85999999999999
492807,342.82
494799,443.13
495322,286.18
495350,118.31
496618,17.0
496872,260.74
497367,279.5
497809,404.54999999999995
498037,404.76000000000005
498291,118.2
499313,365.33000000000004
499684,122.04
499797,599.3000000000002
500459,309.26
500838,249.20999999999987
501800,595.8000000000001
501812,308.96
503337,337.78000000000003
503670,128.7
503696,22.180000000000007
504329,92.39999999999999
504826,354.24
504910,618.5400000000001
505064,204.74999999999997
505362,183.29999999999998
507159,114.21
507403,196.2399999999999
508466,92.8
508731,324.78
509766,187.62999999999997
509953,304.74
510016,337.19999999999993
511549,206.20000000000002
512949,255.37
513369,453.9600000000001
514333,39.8
514943,138.35000000000002
515290,248.17999999999995
489834,214.79999999999998
490163,141.63000000000002
490769,221.0
491403,616.53
492409,189.31
492640,421.40000000000003
492839,673.12
493755,57.599999999999994
495182,269.91
495280,323.65
495375,409.92999999999995
495545,93.63999999999999
495732,96.46
496459,364.29
499240,4.25
499676,389.78000000000003
500590,212.0
501004,366.69000000000005
501102,615.6100000000001
501799,134.86
502278,395.22999999999996
504923,139.35
505068,412.32000000000005
505871,221.26999999999998
505986,347.76000000000005
506252,229.04999999999998
506466,94.45
506909,250.92
507394,335.85
508503,237.78
509205,15.549999999999999
509874,170.95
510353,217.73
510667,504.0
510839,232.55
512425,151.98000000000002
491062,124.0
492230,60.48
492436,329.58
492751,316.59000000000003
493398,66.9
493972,327.6
495758,274.2
495884,148.85
497252,404.9100000000002
498150,28.2
500132,513.05
500165,478.50000000000006
500256,400.13
500287,157.73999999999998
501551,132.73000000000002
502110,301.85999999999996
502268,117.04999999999998
502424,330.15
503167,92.16
503358,305.0
503534,151.46
504862,350.4
505175,153.28
505211,422.75
505342,276.71000000000004
505712,564.5699999999997
505855,456.86999999999995
505874,143.45000000000002

Databricks visualization. Run in Databricks to view.

## Monthly Placed and Canceled Orders

In [0]:
%python
from pyspark.sql.functions import sum, when, date_format

retail_df = retail_df.withColumn(
    "amount", col("quantity") * col("unit_price")
)

invoice_totals = (
    retail_df
    .groupBy("invoice_no", "invoice_date")
    .agg(sum("amount").alias("total_amount"))
)

invoice_totals = invoice_totals.withColumn(
    "is_cancelled",
    col("total_amount") < 0
)

invoice_totals = invoice_totals.withColumn(
    "InvoiceYearMonth",
    date_format(col("invoice_date"), "yyyy-MM")
)

summary = (
    invoice_totals
    .groupBy("InvoiceYearMonth")
    .agg(
        sum(when(~col("is_cancelled"), 1).otherwise(0)).alias("Placement"),
        sum(when(col("is_cancelled"), 1).otherwise(0)).alias("Cancellation")
    )
)

summary = summary.withColumn(
    "Placement",
    col("Placement") - col("Cancellation")
)

In [0]:
%python
display(summary)

InvoiceYearMonth,Placement,Cancellation
2010-08,1340,273
2010-11,2524,576
2010-02,1491,239
2010-04,1284,305
2011-05,1539,314
2010-03,1558,407
2010-01,1034,300
2010-09,1642,371
2010-06,1504,357
2011-03,1352,319
2010-07,1328,345
2011-01,963,260
2011-11,2583,441
2011-08,1179,280
2011-04,1270,240
2011-09,1662,333
2011-07,1388,270
2011-10,1914,362
2009-12,1529,401
2010-05,1605,407
2011-02,963,219
2011-06,1355,329
2010-12,1374,326
2011-12,723,146
2010-10,2013,477

Databricks visualization. Run in Databricks to view.

## Monthly Sales

In [0]:
%python
retail_df = retail_df.withColumn(
    "InvoiceYearMonth",
    date_format(col("invoice_date"), "yyyy-MM")
)

monthly_sales = (
    retail_df
    .groupBy("InvoiceYearMonth")
    .agg(sum("amount").alias("amount"))
)

display(monthly_sales)

InvoiceYearMonth,amount
2010-02,533091.4260000042
2010-04,590580.4319999823
2010-03,765848.7609999765
2010-01,624032.8919999955
2010-06,679786.6099999842
2010-07,575236.3600000103
2009-12,799847.1100000143
2010-05,615322.8300000005
2011-05,723333.5100000103
2011-03,683267.0800000189
2011-01,560000.2600000234
2011-11,1461756.2499997574
2011-08,682680.5100000178
2011-04,493207.12100002496
2011-09,1019687.6220000109
2011-10,1070704.6699999748
2011-07,681300.11100003
2011-02,498062.6500000268
2011-06,691123.1200000227
2010-12,1126445.4699999832
2010-08,656776.3399999854
2010-11,1422654.6419998254
2010-09,853650.4309999745
2010-10,1045168.3499998983
2011-12,433686.01000001706

Databricks visualization. Run in Databricks to view.

## Monthly Sales Growth

In [0]:
%python
from pyspark.sql.window import Window
from pyspark.sql.functions import lag

window_spec = Window.orderBy("InvoiceYearMonth")

monthly_growth = monthly_sales.withColumn(
    "pct_change",
    (col("amount") - lag("amount").over(Window.orderBy("InvoiceYearMonth"))) /
    lag("amount").over(Window.orderBy("InvoiceYearMonth"))
)

display(monthly_growth)

InvoiceYearMonth,amount,pct_change
2009-12,799847.1100000143,null
2010-01,624032.8919999955,-0.21980978089677128
2010-02,533091.4260000042,-0.14573184709627765
2010-03,765848.7609999765,0.4366180426994347
2010-04,590580.4319999823,-0.22885501410375667
2010-05,615322.8300000005,0.0418950521544184
2010-06,679786.6099999842,0.10476416095268813
2010-07,575236.3600000103,-0.153798631014483
2010-08,656776.3399999854,0.1417503928297815
2010-09,853650.4309999745,0.29975819622246663
2010-10,1045168.3499998983,0.22435169250202086
2010-11,1422654.6419998254,0.36117271633796005
2010-12,1126445.4699999832,-0.20820876919465217
2011-01,560000.2600000234,-0.5028607465570155
2011-02,498062.6500000268,-0.11060282364867835
2011-03,683267.0800000189,0.3718496659004287
2011-04,493207.12100002496,-0.2781634950127975
2011-05,723333.5100000103,0.46659178102169707
2011-06,691123.1200000227,-0.04453048221143121
2011-07,681300.11100003,-0.014213110104017967
2011-08,682680.5100000178,0.002026124724919952
2011-09,1019687.6220000109,0.4936527512701136
2011-10,1070704.6699999748,0.05003203618368853
2011-11,1461756.2499997574,0.36522823796013876
2011-12,433686.01000001706,-0.7033116773059195

Databricks visualization. Run in Databricks to view.

## Monthly Active Users

In [0]:
%python
from pyspark.sql.functions import countDistinct

monthly_active_users = (retail_df.groupBy("InvoiceYearMonth").agg(countDistinct("customer_id").alias("active_users")))

display(monthly_active_users)

InvoiceYearMonth,active_users
2010-08,964
2010-11,1683
2010-02,807
2010-04,998
2011-05,1079
2010-03,1111
2010-01,786
2010-09,1202
2010-06,1095
2011-03,1020
2010-07,988
2011-01,783
2011-11,1711
2011-08,980
2011-04,899
2011-09,1302
2011-07,993
2011-10,1425
2009-12,1045
2010-05,1062
2011-02,798
2011-06,1051
2010-12,948
2011-12,686
2010-10,1577

Databricks visualization. Run in Databricks to view.

## New and Existing Users

In [0]:
%python

first_purchase = (
  retail_df.groupby("customer_id").agg(min("InvoiceYearMonth").alias("FirstPurchaseMonth"))
)

retail_df_copy = retail_df.join(first_purchase, on="customer_id", how="left")

retail_df_copy = retail_df_copy.withColumn("NewUser", col("InvoiceYearMonth") == col("FirstPurchaseMonth"))

monthly_users = (
  retail_df_copy
  .dropDuplicates(["customer_id", "InvoiceYearMonth"])
  .groupby("InvoiceYearMonth")
  .pivot("NewUser")
  .agg(countDistinct("customer_id"))
  .fillna(0)
)

monthly_users = monthly_users.selectExpr(
    "InvoiceYearMonth",
    "`true` as NewUserCount",
    "`false` as ExUserCount"
)

In [0]:
%python
display(monthly_users)

InvoiceYearMonth,NewUserCount,ExUserCount
2010-08,158,806
2010-11,322,1361
2010-02,363,444
2010-04,291,707
2011-05,108,971
2010-03,436,675
2010-01,394,392
2010-09,242,960
2010-06,269,826
2011-03,178,842
2010-07,183,805
2011-01,71,712
2011-11,192,1519
2011-08,106,874
2011-04,105,794
2011-09,187,1115
2011-10,221,1204
2011-07,102,891
2009-12,1045,0
2010-05,254,808
2011-06,108,943
2011-02,123,675
2010-12,77,871
2011-12,28,658
2010-10,379,1198

Databricks visualization. Run in Databricks to view.

## RFM Segmentation

### Data Preparation

In [0]:
%python
from pyspark.sql.functions import lit, to_date

today = to_date(lit("2011-12-31"))

retail_df = retail_df.filter((col("quantity") > 0) & (col("unit_price") > 0))
retail_df = retail_df.na.drop()
retail_df.toPandas().describe([0.01, 0.05, 0.10, 0.25, 0.50, 0.75, 0.90, 0.95, 0.99]).T

                count          mean          std  ...      95%       99%       max
quantity     805549.0     13.290522   143.634088  ...     36.0    128.00   80995.0
unit_price   805549.0      3.206561    29.199173  ...      8.5     14.95   10953.5
customer_id  805549.0  15331.954970  1696.737039  ...  17913.0  18204.00   18287.0
amount       805549.0     22.026505   224.041928  ...     67.5    201.60  168469.6

[4 rows x 14 columns]

### Finding RFM Score
RFM consists of Recency, Frequency, Monetary initials of expressions.

It is a technique that helps determine marketing and sales strategies based on buying habits of customers.

Recency: Time since customer last purchase

Frequency: Total number of purchases.

Monetary: Total spending by the customer.

In [0]:
%python
from pyspark.sql.functions import datediff
# finding Recency and Monetary values.
df_x = (
    retail_df
    .groupBy("customer_id")
    .agg(
        sum("amount").alias("amount_x"),
        datediff(today, max("invoice_date")).alias("invoice_date")
    )
)  # recency value
# x.max()).days; last shopping date of customers

In [0]:
%python
from pyspark.sql.functions import count
df_y = retail_df.groupby("customer_id", "invoice_no").agg(sum("amount").alias("amount"))
df_z = df_y.groupby("customer_id").agg(count("amount").alias("amount_y"))
# finding the frequency value per capita

In [0]:
%python
# creating the RFM table
rfm_table = df_x.join(df_z, on="customer_id", how="inner")

In [0]:
%python
rfm_table = (
  rfm_table
    .withColumnRenamed("invoice_date", "Recency")
    .withColumnRenamed("amount_x", "Monetary")
    .withColumnRenamed("amount_y", "Frequency")
)

In [0]:
%python
from pyspark.sql.functions import ntile, concat_ws

recency_window = Window.orderBy(col("Recency").desc())
freq_window = Window.orderBy(col("Frequency").asc())
monetary_window = Window.orderBy(col("Monetary").asc())

rfm_table = (
            rfm_table
             .withColumn("RecencyScore", ntile(5).over(recency_window))
             .withColumn("FrequencyScore", ntile(5).over(freq_window))
             .withColumn("MonetaryScore", ntile(5).over(monetary_window))
             )

rfm_table = rfm_table.withColumn(
    "RFM_SCORE",
    concat_ws("", col("RecencyScore"), col("FrequencyScore"), col("MonetaryScore"))
)

In [0]:
%python
rfm_table = rfm_table.withColumn(
    "Segment",
    concat_ws("", col("RecencyScore"), col("FrequencyScore"))
)

from pyspark.sql.functions import when

rfm_table = rfm_table.withColumn(
    "Segment",
    when(col("Segment").rlike(r"[1-2][1-2]"), "Hibernating")
    .when(col("Segment").rlike(r"[1-2][3-4]"), "At Risk")
    .when(col("Segment").rlike(r"[1-2]5"), "Can't Lose")
    .when(col("Segment").rlike(r"3[1-2]"), "About to Sleep")
    .when(col("Segment").rlike(r"33"), "Need Attention")
    .when(col("Segment").rlike(r"[3-4][4-5]"), "Loyal Customers")
    .when(col("Segment").rlike(r"41"), "Promising")
    .when(col("Segment").rlike(r"51"), "New Customers")
    .when(col("Segment").rlike(r"[4-5][2-3]"), "Potential Loyalists")
    .when(col("Segment").rlike(r"5[4-5]"), "Champions")
    .otherwise("Other")
)

In [0]:
%python
summary = (
    rfm_table
    .groupBy("Segment")
    .agg(
        mean("Recency").alias("Recency_mean"),
        mean("Frequency").alias("Frequency_mean"),
        mean("Monetary").alias("Monetary_mean"),
        count("Recency").alias("Recency_count"),
        count("Frequency").alias("Frequency_count"),
        count("Monetary").alias("Monetary_count")
    )
)
display(summary)

Segment,Recency_mean,Frequency_mean,Monetary_mean,Recency_count,Frequency_count,Monetary_count
Hibernating,477.1611922141119,1.3065693430656935,449.9006763990271,1644,1644,1644
About to Sleep,129.04534606205252,1.4128878281622912,538.3337303102629,419,419,419
Potential Loyalists,48.48754914809961,2.0288335517693317,932.6087811271293,763,763,763
At Risk,385.5357142857143,4.298136645962733,1535.6636801242223,644,644,644
Need Attention,133.9892086330935,3.449640287769784,1359.2972661870494,278,278,278
Loyal Customers,84.56308213378493,9.831498729889924,4200.169547840811,1181,1181,1181
Champions,30.023728813559323,18.381920903954803,10355.231079096044,885,885,885
Can't Lose,351.84375,16.796875,8984.66159375,64,64,64

### Remark:
3 segments selected for evaluation are "Can't Lose", "Hibernating" and "Champions".

Number of customers for segments:

Can't Lose = 64, Hibernating = 1644, Champions = 885

Can't Lose Segment;

The last shopping date of the customers is on average 352 days before.
Customers have made an average of 17 purchases.
Customers spent an average of £ 8995.
Hibernating Segment;

The last shopping date of the customers is 477 days before average.
Customers made an average of 1 purchases.
Customers spent an average of £ 450.
Champions Segment;

The last shopping date of the customers is 30 days before average.
Customers made an average of 18 purchases.
Customers spent an average of £ 10355.
Can't Lose Segment;

Customers in this segment have not recently made a purchase. For this reason, we need to prepare a discount and gift campaign for this segment. These customers made a large number of purchases when they made purchases before. However, recency values are lower than they should be. The campaign to be implemented for these customers should include both items purchased and recommendations based on previous activities. New and popular products associated with the products that they were interested in can also be included in this campaign. Situations that will cause these customers to stop buying need to be investigated.
Hibernating Segment;

Customers in this segment have not made a purchase for a long time. However, by offering discounts, they may be attracted to another purchase.
Champions Segment;

Customers in this segment are responsible for most of the revenue. Campaigns should be implemented to ensure the continuity of the shopping of these customers.